const fs = require("fs");

// Read existing HTML
const htmlRaw = fs.readFileSync("C:/Users/alfre/Desktop/free-dynamic-qr/public/index.html", "utf8");
// Remove backticks (replace with apostrophe - safe in HTML)
const html = htmlRaw.replace(/`/g, "\u0060".replace("\u0060","'"));

// Base64 encode - completely safe string, no special chars
const b64 = Buffer.from(html, "utf8").toString("base64");

const worker = [
"// free-dynamic-qr — Cloudflare Worker (v4)",
"// Copy/paste this entire file in the Cloudflare Workers editor.",
"// Repo: https://github.com/alfredgabriel/free-dynamic-qr",
"",
'// HTML panel encoded in base64 to avoid any syntax conflicts',
'const PANEL_B64 = "' + b64 + '";',
'function getHTML() {',
'  // Decode base64 to UTF-8 HTML string',
'  var b = atob(PANEL_B64);',
'  var bytes = new Uint8Array(b.length);',
'  for (var i = 0; i < b.length; i++) bytes[i] = b.charCodeAt(i);',
'  return new TextDecoder().decode(bytes);',
'}',
"",
"async function hashPassword(pw) {",
"  var salt = crypto.getRandomValues(new Uint8Array(16));",
"  var key = await crypto.subtle.importKey('raw', new TextEncoder().encode(pw), 'PBKDF2', false, ['deriveBits']);",
"  var bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: salt, iterations: 100000, hash: 'SHA-256' }, key, 256);",
"  var h = function(a) { return Array.from(a).map(function(b) { return b.toString(16).padStart(2, '0'); }).join(''); };",
"  return h(salt) + ':' + h(new Uint8Array(bits));",
"}",
"",
"async function verifyPassword(pw, stored) {",
"  try {",
"    var p = stored.split(':');",
"    var salt = new Uint8Array(p[0].match(/.{2}/g).map(function(b) { return parseInt(b, 16); }));",
"    var key = await crypto.subtle.importKey('raw', new TextEncoder().encode(pw), 'PBKDF2', false, ['deriveBits']);",
"    var bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: salt, iterations: 100000, hash: 'SHA-256' }, key, 256);",
"    return Array.from(new Uint8Array(bits)).map(function(b) { return b.toString(16).padStart(2, '0'); }).join('') === p[1];",
"  } catch(e) { return false; }",
"}",
"",
"async function createToken(ref) {",
"  var p = String(Date.now());",
"  var key = await crypto.subtle.importKey('raw', new TextEncoder().encode(ref.slice(0, 32)), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);",
"  var sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(p));",
"  return p + '.' + Array.from(new Uint8Array(sig)).map(function(b) { return b.toString(16).padStart(2, '0'); }).join('');",
"}",
"",
"async function verifyToken(tok, ref) {",
"  try {",
"    var p = tok.split('.');",
"    var key = await crypto.subtle.importKey('raw', new TextEncoder().encode(ref.slice(0, 32)), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);",
"    var sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(p[0]));",
"    return Array.from(new Uint8Array(sig)).map(function(b) { return b.toString(16).padStart(2, '0'); }).join('') === p[1];",
"  } catch(e) { return false; }",
"}",
"",
"export default {",
"  async fetch(request, env) {",
"    var url = new URL(request.url);",
"    var path = url.pathname;",
"    var cors = {",
"      'Access-Control-Allow-Origin': '*',",
"      'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',",
"      'Access-Control-Allow-Headers': 'Content-Type,Authorization'",
"    };",
"    function json(d, s) {",
"      return new Response(JSON.stringify(d), { status: s || 200, headers: Object.assign({}, cors, { 'Content-Type': 'application/json' }) });",
"    }",
"    if (request.method === 'OPTIONS') return new Response(null, { headers: cors });",
"    if (path === '/' || path === '/admin' || path === '') {",
"      return new Response(getHTML(), { headers: { 'Content-Type': 'text/html; charset=utf-8' } });",
"    }",
"    if (!env.QR_KV) {",
"      return json({ error: 'KV binding missing. In Worker > Bindings, add a KV namespace with variable name QR_KV.' }, 500);",
"    }",
"    try {",
"      if (path === '/api/setup' && request.method === 'POST') {",
"        var body = await request.json();",
"        if (body.__check) {",
"          var ex = await env.QR_KV.get('config:password');",
"          return json(ex ? { configured: true } : { notSetup: true });",
"        }",
"        var existing = await env.QR_KV.get('config:password');",
"        if (existing) return json({ error: 'Already configured.' }, 403);",
"        if (!body.password || body.password.length < 6) return json({ error: 'Min 6 characters.' }, 400);",
"        await env.QR_KV.put('config:password', await hashPassword(body.password));",
"        return json({ ok: true });",
"      }",
"      if (path === '/api/login' && request.method === 'POST') {",
"        var body = await request.json();",
"        var stored = await env.QR_KV.get('config:password');",
"        if (!stored) return json({ error: 'Not set up yet.' }, 400);",
"        if (!await verifyPassword(body.password, stored)) return json({ error: 'Incorrect password.' }, 401);",
"        return json({ token: await createToken(stored) });",
"      }",
"      if (path.startsWith('/r/')) {",
"        var slug = path.slice(3).replace(/[/]$/, '');",
"        if (!slug) return Response.redirect(url.origin, 302);",
"        var data = await env.QR_KV.get('qr:' + slug, 'json');",
"        if (!data || !data.url) return new Response('QR not found.', { status: 404 });",
"        try {",
"          var up = Object.assign({}, data, { scans: (data.scans || 0) + 1, lastScan: new Date().toISOString() });",
"          await env.QR_KV.put('qr:' + slug, JSON.stringify(up));",
"        } catch(e) {}",
"        return Response.redirect(data.url, 302);",
"      }",
"      var tok = (request.headers.get('Authorization') || '').replace('Bearer ', '');",
"      var stored = await env.QR_KV.get('config:password');",
"      if (!stored || !tok || !await verifyToken(tok, stored)) return json({ error: 'Unauthorized.' }, 401);",
"      if (path === '/api/qrs' && request.method === 'GET') {",
"        var list = await env.QR_KV.list({ prefix: 'qr:' });",
"        var qrs = await Promise.all(list.keys.map(async function(k) {",
"          var d = await env.QR_KV.get(k.name, 'json');",
"          return d ? Object.assign({ slug: k.name.replace('qr:', '') }, d) : null;",
"        }));",
"        return json(qrs.filter(Boolean));",
"      }",
"      if (path === '/api/qrs' && request.method === 'POST') {",
"        var body = await request.json();",
"        if (!body.slug || !body.url) return json({ error: 'slug and url required.' }, 400);",
"        var clean = body.slug.toLowerCase().replace(/[^a-z0-9_-]/g, '');",
"        if (!clean) return json({ error: 'Invalid slug.' }, 400);",
"        if (await env.QR_KV.get('qr:' + clean)) return json({ error: 'Slug already in use.' }, 409);",
"        var entry = { url: body.url, label: body.label || clean, scans: 0, createdAt: new Date().toISOString(), lastScan: null };",
"        await env.QR_KV.put('qr:' + clean, JSON.stringify(entry));",
"        return json(Object.assign({ slug: clean }, entry), 201);",
"      }",
"      if (path.startsWith('/api/qrs/') && request.method === 'PUT') {",
"        var slug = path.slice(9);",
"        var data = await env.QR_KV.get('qr:' + slug, 'json');",
"        if (!data) return json({ error: 'QR not found.' }, 404);",
"        var body = await request.json();",
"        var upd = Object.assign({}, data,",
"          body.url ? { url: body.url } : {},",
"          body.label ? { label: body.label } : {},",
"          { updatedAt: new Date().toISOString() }",
"        );",
"        await env.QR_KV.put('qr:' + slug, JSON.stringify(upd));",
"        return json(Object.assign({ slug: slug }, upd));",
"      }",
"      if (path.startsWith('/api/qrs/') && request.method === 'DELETE') {",
"        await env.QR_KV.delete('qr:' + path.slice(9));",
"        return json({ ok: true });",
"      }",
"      return json({ error: 'Not found.' }, 404);",
"    } catch(err) {",
"      return json({ error: 'Worker error: ' + err.message }, 500);",
"    }",
"  }",
"};",
].join("\n");

fs.writeFileSync("C:/Users/alfre/Desktop/free-dynamic-qr/worker.js", worker, "utf8");
console.log("Done! Lines:", worker.split("\n").length, "Size:", worker.length);
